services:
  requestform-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: requestform-server
    container_name: requestform-server
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
     # - ./storage:/var/www/storage
     # - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf
      - /mnt/nvme0n1/requestUploads:/mnt/nvme0n1/requestUploads

    networks:
      - requestform-server
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1  # Replace with your host's IP if necessary
      DB_PORT: 3306
      DB_DATABASE: requestform
      DB_USERNAME: smct
      DB_PASSWORD: smct 

  requestform-nginx:
    image: nginx:alpine
    container_name: requestform-nginx
    restart: unless-stopped
    ports:
      - 8004:8004
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf
      - ./:/var/www
      - /mnt/nvme0n1/requestUploads:/mnt/nvme0n1/requestUploads

    networks:
      - requestform-server


networks:
  requestform-server:
    driver: bridge
